#server.port=80

#自定义的配置参数
myUploadPath: E:/ba1/

#服务器端口：80
server:
  port: 80

spring:
#连接数据库配置  
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/c76-s3-phooy-blog
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver
  #静态资源映射
  resources:
    staticLocations:
      - classpath:/resources/
      - classpath:/static/
      - file:d:${myUploadPath}
  #文件上传大小限制
  servlet:
    multipart:
      maxFileSize: 10000000

#mybatis
mybatis:
  #实体类别名 com.yc.C76S3PlySpringBoot.bean -> bean
  type-aliases-package: com.yc.blog.bean
  #驼峰命名法 类成员别名
  configuration:
    map-underscore-to-camel-case: true

#测试类配置  
logging:
  level:
    com:
      yc:
        blog:
          dao: debug
          web: warn